# League of Legends Patch Notes + Champion Updates Scraper

这个 Notebook 用于：
1. 自动翻页抓取英雄联盟官网 Patch Notes 历史条目
2. 进入每一篇 Patch Note，解析其中提到的英雄和对应更新内容
3. 输出整合后的 DataFrame 和 CSV

目标页面：
`https://www.leagueoflegends.com/en-us/news/tags/patch-notes/`

In [6]:
import json
import re
import time
from typing import Dict, List
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup

BASE_URL = "https://www.leagueoflegends.com"
PATCH_NOTES_URL = "https://www.leagueoflegends.com/en-us/news/tags/patch-notes/"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
}

In [7]:
def get_next_data(url: str) -> Dict:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    script = soup.find("script", id="__NEXT_DATA__")
    if not script or not script.string:
        raise ValueError(f"No __NEXT_DATA__ found for: {url}")

    return json.loads(script.string)


def extract_patch_items(next_data: Dict) -> List[Dict]:
    blades = next_data.get("props", {}).get("pageProps", {}).get("page", {}).get("blades", [])
    article_grid = next((b for b in blades if b.get("type") == "articleCardGrid"), None)
    if not article_grid:
        return []

    records = []
    for item in article_grid.get("items", []):
        title = (item.get("title") or "").strip()
        if not title or "patch" not in title.lower():
            continue

        rel_url = item.get("action", {}).get("payload", {}).get("url", "")
        if not rel_url:
            continue

        full_url = urljoin(BASE_URL, rel_url)
        published_at = item.get("publishedAt")

        raw_description = item.get("description")
        if isinstance(raw_description, str):
            summary = raw_description.strip()
        elif isinstance(raw_description, dict):
            # description 有时是富文本对象，转纯文本
            summary = re.sub(r"\s+", " ", BeautifulSoup(str(raw_description), "html.parser").get_text(" ", strip=True)).strip()
        else:
            summary = ""

        records.append(
            {
                "title": title,
                "url": full_url,
                "published_at": published_at,
                "summary": summary,
            }
        )

    return records


def crawl_patch_notes(max_pages: int = 50, sleep_sec: float = 0.25) -> pd.DataFrame:
    all_records = []
    seen_urls = set()

    for page in range(1, max_pages + 1):
        page_url = PATCH_NOTES_URL if page == 1 else f"{PATCH_NOTES_URL}?page={page}"

        try:
            next_data = get_next_data(page_url)
        except Exception as e:
            print(f"Stop at page {page}: {e}")
            break

        page_records = extract_patch_items(next_data)
        if not page_records:
            print(f"No records on page {page}, stop.")
            break

        new_count = 0
        for row in page_records:
            if row["url"] in seen_urls:
                continue
            seen_urls.add(row["url"])
            all_records.append(row)
            new_count += 1

        print(f"Page {page}: fetched={len(page_records)}, new={new_count}, total={len(all_records)}")

        # 如果新页面没有带来新数据，说明没有真实翻页数据了
        if new_count == 0:
            break

        time.sleep(sleep_sec)

    df_patches = pd.DataFrame(all_records)
    if not df_patches.empty:
        df_patches["published_at"] = pd.to_datetime(df_patches["published_at"], errors="coerce", utc=True)
        df_patches = df_patches.sort_values("published_at", ascending=False).reset_index(drop=True)

    return df_patches


patch_df = crawl_patch_notes(max_pages=100)
patch_df.head(20), len(patch_df)

Page 1: fetched=162, new=162, total=162
Page 2: fetched=162, new=0, total=162

(                                 title  \
 0   League of Legends Patch 26.7 Notes
 1   League of Legends Patch 26.6 Notes
 2   League of Legends Patch 26.5 Notes
 3   League of Legends Patch 26.4 Notes
 4                     Patch 26.3 Notes
 5                     Patch 26.2 Notes
 6                     Patch 26.1 Notes
 7                    Patch 25.24 Notes
 8                    Patch 25.23 Notes
 9                    Patch 25.22 Notes
 10                   Patch 25.21 Notes
 11                   Patch 25.20 Notes
 12                   Patch 25.19 Notes
 13                   Patch 25.18 Notes
 14                   Patch 25.17 Notes
 15                   Patch 25.16 Notes
 16                   Patch 25.15 Notes
 17                   Patch 25.14 Notes
 18                   Patch 25.13 Notes
 19                   Patch 25.12 Notes

                                                   url  \
 0   https://www.leagueoflegends.com/en-us/news/gam...
 1   https://www.leagueoflegends.com/en-us/news/gam...
 2   https://www.leagueoflegends.com/en-us/news/gam...
 3   https://www.leagueoflegends.com/en-us/news/gam...
 4   https://www.leagueoflegends.com/en-us/news/gam...
 5   https://www.leagueoflegends.com/en-us/news/gam...
 6   https://www.leagueoflegends.com/en-us/news/gam...
 7   https://www.leagueoflegends.com/en-us/news/gam...
 8   https://www.leagueoflegends.com/en-us/news/gam...
 9   https://www.leagueoflegends.com/en-us/news/gam...
 10  https://www.leagueoflegends.com/en-us/news/gam...
 11  https://www.leagueoflegends.com/en-us/news/gam...
 12  https://www.leagueoflegends.com/en-us/news/gam...
 13  https://www.leagueoflegends.com/en-us/news/gam...
 14  https://www.leagueoflegends.com/en-us/news/gam...
 15  https://www.leagueoflegends.com/en-us/news/gam...
 16  https://www.leagueoflegends.com/en-us/news/gam...
 17  https://www.leagueoflegends.com/en-us/news/gam...
 18  https://www.leagueoflegends.com/en-us/news/gam...
 19  https://www.leagueoflegends.com/en-us/news/gam...

                 published_at  \
 0  2026-03-31 18:00:00+00:00
 1  2026-03-17 18:00:00+00:00
 2  2026-03-03 19:00:00+00:00
 3  2026-02-18 19:00:00+00:00
 4  2026-02-03 19:00:00+00:00
 5  2026-01-21 19:00:00+00:00
 6  2026-01-07 19:00:00+00:00
 7  2025-12-02 19:00:00+00:00
 8  2025-11-18 19:00:00+00:00
 9  2025-11-04 19:00:00+00:00
 10 2025-10-21 18:00:00+00:00
 11 2025-10-07 18:00:00+00:00
 12 2025-09-23 18:00:00+00:00
 13 2025-09-09 18:00:00+00:00
 14 2025-08-26 18:00:00+00:00
 15 2025-08-12 18:00:00+00:00
 16 2025-07-29 18:00:00+00:00
 17 2025-07-15 18:00:00+00:00
 18 2025-06-24 18:00:00+00:00
 19 2025-06-10 18:05:00+00:00

                                               summary
 0   {'type': 'html', 'body': 'Tons of fun and frie...
 1   {'type': 'html', 'body': 'It’s time for First ...
 2   {'type': 'html', 'body': 'Welcome to the offic...
 3   {'type': 'html', 'body': 'Happy Lunar Revel, w...
 4   {'type': 'html', 'body': 'Celebrate the new ye...
 5   {'type': 'html', 'body': 'Patch 26.2 ready to ...
 6   {'type': 'html', 'body': 'Demacia rises in Pat...
 7   {'type': 'html', 'body': 'The last patch of th...
 8   {'type': 'html', 'body': 'Patch 25.23 has asce...
 9   {'type': 'html', 'body': 'We’re going to Cheng...
 10  {'type': 'html', 'body': 'Patch 25.21 is bee-a...
 11  {'type': 'html', 'body': 'Get ready for Worlds...
 12  {'type': 'html', 'body': 'Your fate is sealed ...
 13  {'type': 'html', 'body': 'Celebrate patch 25.1...
 14  {'type': 'html', 'body': 'Your fortune looks g...
 15  {'type': 'html', 'body': 'Patch 25.16 ready fo...
 16  {'type': 'html', 'body': 'Patch 25.15 is unbot...
 17  {'type': 'html', 'body': 'Test your resolve wi...
 18  {'type': 'html', 'body': 'Wyldbloom has entere...
 19  {'type': 'html', 'body': 'Welcome to the Hall ...  ,
 162)

In [8]:
CHAMPION_EXCLUDE_KEYWORDS = {
    "patch highlights",
    "related articles",
    "systems",
    "items",
    "runes",
    "aram",
    "arena",
    "ranked",
    "skins",
    "chromas",
    "mythic shop",
    "quality of life",
    "bugfixes",
    "bug fixes",
    "tft",
}


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "")).strip()


def looks_like_champion_name(text: str) -> bool:
    t = clean_text(text)
    if not t:
        return False

    lower = t.lower()
    if lower in CHAMPION_EXCLUDE_KEYWORDS:
        return False

    if len(t) > 40:
        return False

    if any(sym in t for sym in ["/", "(", ")", "[", "]", "{", "}", ":"]):
        return False

    # 能力小节常见格式："Q - Name"
    if " - " in t:
        return False

    allowed = re.compile(r"^[A-Za-z0-9'&.\- ]+$")
    if not allowed.match(t):
        return False

    return True


def parse_champion_updates_from_article(url: str) -> List[Dict]:
    try:
        resp = requests.get(url, headers=HEADERS, timeout=30)
        resp.raise_for_status()
    except Exception as e:
        print(f"Failed to fetch {url}: {e}")
        return []

    soup = BeautifulSoup(resp.text, "html.parser")
    main = soup.find("main") or soup

    updates = []
    champion_lines: Dict[str, List[str]] = {}

    in_champion_section = False
    current_champion = None

    stream_tags = main.find_all(["h2", "h3", "h4", "p", "li"])

    for tag in stream_tags:
        tag_name = tag.name.lower()
        text = clean_text(tag.get_text(" ", strip=True))
        if not text:
            continue

        if tag_name == "h2":
            lower = text.lower()

            # 进入冠军改动区域（如：Champions / Champion Buffs / Champion Nerfs）
            if "champion" in lower:
                in_champion_section = True
                current_champion = None
                continue

            # 离开冠军改动区域
            if in_champion_section:
                in_champion_section = False
                current_champion = None

            continue

        if not in_champion_section:
            continue

        # 英雄名以 h3 为主，能明显减少把 "Base Stats" 这类小节标题误判成英雄
        if tag_name == "h3" and looks_like_champion_name(text):
            current_champion = text
            champion_lines.setdefault(current_champion, [])
            continue

        if current_champion and tag_name in {"h4", "p", "li"}:
            # 排除重复英雄名行
            if text == current_champion:
                continue
            champion_lines[current_champion].append(text)

    for champion, lines in champion_lines.items():
        # 去重并保序
        deduped = list(dict.fromkeys([clean_text(x) for x in lines if clean_text(x)]))
        if not deduped:
            continue

        updates.append(
            {
                "champion": champion,
                "champion_update": "\n".join(deduped),
            }
        )

    return updates


MAX_ARTICLES = None  # 调试时可改成 5 或 10，加快运行
source_df = patch_df if MAX_ARTICLES is None else patch_df.head(MAX_ARTICLES)

rows = []
for idx, row in source_df.iterrows():
    print(f"[{idx + 1}/{len(source_df)}] Parsing: {row['title']}")
    champion_updates = parse_champion_updates_from_article(row["url"])

    if not champion_updates:
        continue

    for cu in champion_updates:
        rows.append(
            {
                "patch_title": row["title"],
                "patch_url": row["url"],
                "published_at": row["published_at"],
                "patch_summary": row.get("summary", ""),
                "champion": cu["champion"],
                "champion_update": cu["champion_update"],
            }
        )

champion_updates_df = pd.DataFrame(rows)
if not champion_updates_df.empty:
    champion_updates_df = champion_updates_df.sort_values(
        by=["published_at", "patch_title", "champion"], ascending=[False, True, True]
    ).reset_index(drop=True)

champion_updates_df.head(30), len(champion_updates_df)

[1/162] Parsing: League of Legends Patch 26.7 Notes
[2/162] Parsing: League of Legends Patch 26.6 Notes
[3/162] Parsing: League of Legends Patch 26.5 Notes
[4/162] Parsing: League of Legends Patch 26.4 Notes
[5/162] Parsing: Patch 26.3 Notes
[6/162] Parsing: Patch 26.2 Notes
[7/162] Parsing: Patch 26.1 Notes
[8/162] Parsing: Patch 25.24 Notes
[9/162] Parsing: Patch 25.23 Notes
[10/162] Parsing: Patch 25.22 Notes
[11/162] Parsing: Patch 25.21 Notes
[12/162] Parsing: Patch 25.20 Notes
[13/162] Parsing: Patch 25.19 Notes
[14/162] Parsing: Patch 25.18 Notes
[15/162] Parsing: Patch 25.17 Notes
[16/162] Parsing: Patch 25.16 Notes
[17/162] Parsing: Patch 25.15 Notes
[18/162] Parsing: Patch 25.14 Notes
[19/162] Parsing: Patch 25.13 Notes
[20/162] Parsing: Patch 25.12 Notes
[21/162] Parsing: Patch 25.11 Notes
[22/162] Parsing: Patch 25.10 Notes
[23/162] Parsing: Patch 25.09 Notes
[24/162] Parsing: Patch 25.08 Notes
[25/162] Parsing: Patch 25.07 Notes
[26/162] Parsing: Patch 25.06 Notes
[27/162] Parsing: Patch 25.05 Notes
[28/162] Parsing: Patch 25.04 Notes
[29/162] Parsing: Patch 2025.S1.3 Notes
[30/162] Parsing: Patch 25.S1.2 Notes
[31/162] Parsing: Patch 25.S1.1 Notes
[32/162] Parsing: Patch 14.24 Notes
[33/162] Parsing: Patch 14.23 Notes
[34/162] Parsing: Patch 14.22 Notes
[35/162] Parsing: Patch 14.21 Notes
[36/162] Parsing: Patch 14.20 Notes
[37/162] Parsing: Patch 14.19 Notes
[38/162] Parsing: Patch 14.18 Notes
[39/162] Parsing: Patch 14.17 Notes
[40/162] Parsing: Patch 14.16 Notes
[41/162] Parsing: Patch 14.15 Notes
[42/162] Parsing: Patch 14.14 Notes
[43/162] Parsing: LoL Patch 14.13 Notes
[44/162] Parsing: Patch 14.12 Notes
[45/162] Parsing: Patch 14.11 Notes
[46/162] Parsing: Patch 14.10 Notes
[47/162] Parsing: Patch 14.9 Notes
[48/162] Parsing: Patch 14.8 Notes
[49/162] Parsing: Patch 14.7 Notes
[50/162] Parsing: Patch 14.6 Notes
[51/162] Parsing: Patch 14.5 Notes
[52/162] Parsing: Patch 14.4 Notes
[53/162] Parsing: Patch 14.3 Notes
[54/162] Parsing: Patch 14.2 Notes
[55/162] Parsing: Patch 14.1 Notes
[56/162] Parsing: Patch 13.24 notes
[57/162] Parsing: Patch 13.23 notes
[58/162] Parsing: Patch 13.22 Notes
[59/162] Parsing: Patch 13.21 Notes
[60/162] Parsing: Patch 13.20 Notes
[61/162] Parsing: Patch 13.19 Notes
[62/162] Parsing: Patch 13.18 notes
[63/162] Parsing: Patch 13.17 notes
[64/162] Parsing: Patch 13.16 notes
[65/162] Parsing: Patch 13.15 notes
[66/162] Parsing: Patch 13.14 notes
[67/162] Parsing: Patch 13.13 Notes
[68/162] Parsing: Patch 13.12 notes
[69/162] Parsing: Patch 13.11 notes
[70/162] Parsing: Patch 13.10 notes
[71/162] Parsing: Patch 13.9 notes
[72/162] Parsing: Patch 13.8 notes
[73/162] Parsing: Patch 13.7 Notes
[74/162] Parsing: Patch 13.6 Notes
[75/162] Parsing: Patch 13.5 notes
[76/162] Parsing: Patch 13.4 notes
[77/162] Parsing: Patch 13.3 Notes
[78/162] Parsing: Patch 13.1B notes
[79/162] Parsing: Patch 13.1 notes
[80/162] Parsing: Patch 12.23 notes
[81/162] Parsing: Patch 12.22 notes
[82/162] Parsing: Patch 12.21 notes
[83/162] Parsing: Patch 12.20 notes
[84/162] Parsing: Patch 12.19 notes
[85/162] Parsing: Patch 12.18 notes
[86/162] Parsing: Patch 12.17 notes
[87/162] Parsing: Patch 12.16 Notes
[88/162] Parsing: Patch 12.15 Notes
[89/162] Parsing: Patch 12.14 notes
[90/162] Parsing: Patch 12.13 notes
[91/162] Parsing: Patch 12.12 notes
[92/162] Parsing: Patch 12.11 notes
[93/162] Parsing: Patch 12.10 Notes
[94/162] Parsing: Patch 12.9 Notes
[95/162] Parsing: Patch 12.8 Notes
[96/162] Parsing: Patch 12.7 notes
[97/162] Parsing: Patch 12.6 notes
[98/162] Parsing: Patch 12.5 notes
[99/162] Parsing: Patch 12.4 notes
[100/162] Parsing: Patch 12.3 notes
[101/162] Parsing: Patch 12.2 notes
[102/162] Parsing: Patch 12.1 notes
[103/162] Parsing: Patch 11.24 notes
[104/162] Parsing: Patch 11.23 notes
[105/162] Parsing: Patch 11.22 notes
[106/162] Parsing: Patch 11.21 notes
[107/162] Parsing: Patch 11.20 notes
[108/162] Parsing: Patch 11.19 notes
[109/162] Parsing: Patch 11.18 notes
[110/162] Parsing: Patch 11.17 notes
[111/162] Parsing: Patch 11.16 notes
[112/162] Parsing: Patch 11.15 notes
[113/162] Parsing: Patch 11.14 notes
[114/162] Parsing: Patch 11.13 notes
[115/162] Parsing: Patch 11.12 notes
[116/162] Parsing: Patch 11.11 notes
[117/162] Parsing: Patch 11.10 notes
[118/162] Parsing: Patch 11.9 notes
[119/162] Parsing: Patch 11.8 notes
[120/162] Parsing: Patch 11.7 notes
[121/162] Parsing: Patch 11.6 notes
[122/162] Parsing: Patch 11.5 notes
[123/162] Parsing: Patch 11.4 notes
[124/162] Parsing: Patch 11.3 notes
[125/162] Parsing: Patch 11.2 notes
[126/162] Parsing: Patch 11.1 notes
[127/162] Parsing: Patch 10.25 notes
[128/162] Parsing: Patch 10.24 notes
[129/162] Parsing: Patch 10.23 notes
[130/162] Parsing: Patch 10.22 notes
[131/162] Parsing: Patch 10.21 notes
[132/162] Parsing: Patch 10.20 notes
[133/162] Parsing: Patch 10.19 notes
[134/162] Parsing: Patch 10.18 notes
[135/162] Parsing: Patch 10.17 notes
[136/162] Parsing: Patch 10.16 notes
[137/162] Parsing: Patch 10.15 notes
[138/162] Parsing: Patch 10.14 notes
[139/162] Parsing: Patch 10.13 notes
[140/162] Parsing: Patch 10.12 notes
[141/162] Parsing: Patch 10.11 notes
[142/162] Parsing: Patch 10.10 notes
[143/162] Parsing: Patch 10.9 notes
[144/162] Parsing: Patch 10.8 Notes
[145/162] Parsing: Patch 10.7 notes
[146/162] Parsing: Patch 10.6 notes
[147/162] Parsing: Patch 10.5 notes
[148/162] Parsing: Patch 10.4 Notes
[149/162] Parsing: Patch 10.3 notes
[150/162] Parsing: Patch 10.2 Notes
[151/162] Parsing: Patch 10.1 Notes
[152/162] Parsing: Patch 9.24b notes
[153/162] Parsing: Patch 9.24 notes
[154/162] Parsing: Patch 9.23 notes
[155/162] Parsing: Patch 9.22 notes
[156/162] Parsing: Patch 9.21 notes
[157/162] Parsing: Patch 9.20 notes
[158/162] Parsing: Patch 9.19 notes
[159/162] Parsing: Patch 9.18 Notes
[160/162] Parsing: Patch 9.3 notes
[161/162] Parsing: Patch 9.2 notes
[162/162] Parsing: Patch 9.1 notes

(                           patch_title  \
 0   League of Legends Patch 26.7 Notes
 1   League of Legends Patch 26.7 Notes
 2   League of Legends Patch 26.7 Notes
 3   League of Legends Patch 26.7 Notes
 4   League of Legends Patch 26.7 Notes
 5   League of Legends Patch 26.7 Notes
 6   League of Legends Patch 26.7 Notes
 7   League of Legends Patch 26.7 Notes
 8   League of Legends Patch 26.7 Notes
 9   League of Legends Patch 26.6 Notes
 10  League of Legends Patch 26.6 Notes
 11  League of Legends Patch 26.6 Notes
 12  League of Legends Patch 26.6 Notes
 13  League of Legends Patch 26.6 Notes
 14  League of Legends Patch 26.6 Notes
 15  League of Legends Patch 26.6 Notes
 16  League of Legends Patch 26.6 Notes
 17  League of Legends Patch 26.6 Notes
 18  League of Legends Patch 26.6 Notes
 19  League of Legends Patch 26.5 Notes
 20  League of Legends Patch 26.5 Notes
 21  League of Legends Patch 26.5 Notes
 22  League of Legends Patch 26.5 Notes
 23  League of Legends Patch 26.5 Notes
 24  League of Legends Patch 26.5 Notes
 25  League of Legends Patch 26.5 Notes
 26  League of Legends Patch 26.5 Notes
 27  League of Legends Patch 26.5 Notes
 28  League of Legends Patch 26.5 Notes
 29  League of Legends Patch 26.5 Notes

                                             patch_url  \
 0   https://www.leagueoflegends.com/en-us/news/gam...
 1   https://www.leagueoflegends.com/en-us/news/gam...
 2   https://www.leagueoflegends.com/en-us/news/gam...
 3   https://www.leagueoflegends.com/en-us/news/gam...
 4   https://www.leagueoflegends.com/en-us/news/gam...
 5   https://www.leagueoflegends.com/en-us/news/gam...
 6   https://www.leagueoflegends.com/en-us/news/gam...
 7   https://www.leagueoflegends.com/en-us/news/gam...
 8   https://www.leagueoflegends.com/en-us/news/gam...
 9   https://www.leagueoflegends.com/en-us/news/gam...
 10  https://www.leagueoflegends.com/en-us/news/gam...
 11  https://www.leagueoflegends.com/en-us/news/gam...
 12  https://www.leagueoflegends.com/en-us/news/gam...
 13  https://www.leagueoflegends.com/en-us/news/gam...
 14  https://www.leagueoflegends.com/en-us/news/gam...
 15  https://www.leagueoflegends.com/en-us/news/gam...
 16  https://www.leagueoflegends.com/en-us/news/gam...
 17  https://www.leagueoflegends.com/en-us/news/gam...
 18  https://www.leagueoflegends.com/en-us/news/gam...
 19  https://www.leagueoflegends.com/en-us/news/gam...
 20  https://www.leagueoflegends.com/en-us/news/gam...
 21  https://www.leagueoflegends.com/en-us/news/gam...
 22  https://www.leagueoflegends.com/en-us/news/gam...
 23  https://www.leagueoflegends.com/en-us/news/gam...
 24  https://www.leagueoflegends.com/en-us/news/gam...
 25  https://www.leagueoflegends.com/en-us/news/gam...
 26  https://www.leagueoflegends.com/en-us/news/gam...
 27  https://www.leagueoflegends.com/en-us/news/gam...
 28  https://www.leagueoflegends.com/en-us/news/gam...
 29  https://www.leagueoflegends.com/en-us/news/gam...

                 published_at  \
 0  2026-03-31 18:00:00+00:00
 1  2026-03-31 18:00:00+00:00
 2  2026-03-31 18:00:00+00:00
 3  2026-03-31 18:00:00+00:00
 4  2026-03-31 18:00:00+00:00
 5  2026-03-31 18:00:00+00:00
 6  2026-03-31 18:00:00+00:00
 7  2026-03-31 18:00:00+00:00
 8  2026-03-31 18:00:00+00:00
 9  2026-03-17 18:00:00+00:00
 10 2026-03-17 18:00:00+00:00
 11 2026-03-17 18:00:00+00:00
 12 2026-03-17 18:00:00+00:00
 13 2026-03-17 18:00:00+00:00
 14 2026-03-17 18:00:00+00:00
 15 2026-03-17 18:00:00+00:00
 16 2026-03-17 18:00:00+00:00
 17 2026-03-17 18:00:00+00:00
 18 2026-03-17 18:00:00+00:00
 19 2026-03-03 19:00:00+00:00
 20 2026-03-03 19:00:00+00:00
 21 2026-03-03 19:00:00+00:00
 22 2026-03-03 19:00:00+00:00
 23 2026-03-03 19:00:00+00:00
 24 2026-03-03 19:00:00+00:00
 25 2026-03-03 19:00:00+00:00
 26 2026-03-03 19:00:00+00:00
 27 2026-03-03 19:00:00+00:00
 28 2026-03-03 19:00:00+00:00
 29 2026-03-03 19:00:00+00:00

                                         patch_summary    champion  \
 0   {'type': 'html', 'body': 'Tons of fun and frie...  Cassiopeia
 1   {'type': 'html', 'body': 'Tons of fun and frie...      Graves
 2   {'type': 'html', 'body': 'Tons of fun and frie...     Kalista
 3   {'type': 'html', 'body': 'Tons of fun and frie...       Karma
 4   {'type': 'html', 'body': 'Tons of fun and frie...        Nami
 5   {'type': 'html', 'body': 'Tons of fun and frie...        Ornn
 6   {'type': 'html', 'body': 'Tons of fun and frie...        Rell
 7   {'type': 'html', 'body': 'Tons of fun and frie...      Singed
 8   {'type': 'html', 'body': 'Tons of fun and frie...      Veigar
 9   {'type': 'html', 'body': 'It’s time for First ...        Ahri
 10  {'type': 'html', 'body': 'It’s time for First ...        Azir
 11  {'type': 'html', 'body': 'It’s time for First ...  Cassiopeia
 12  {'type': 'html', 'body': 'It’s time for First ...   Lissandra
 13  {'type': 'html', 'body': 'It’s time for First ...        Olaf
 14  {'type': 'html', 'body': 'It’s time for First ...        Pyke
 15  {'type': 'html', 'body': 'It’s time for First ...        Shen
 16  {'type': 'html', 'body': 'It’s time for First ...     Skarner
 17  {'type': 'html', 'body': 'It’s time for First ...  Tryndamere
 18  {'type': 'html', 'body': 'It’s time for First ...      Zaahen
 19  {'type': 'html', 'body': 'Welcome to the offic...       Akali
 20  {'type': 'html', 'body': 'Welcome to the offic...        Azir
 21  {'type': 'html', 'body': 'Welcome to the offic...       Garen
 22  {'type': 'html', 'body': 'Welcome to the offic...     Lee Sin
 23  {'type': 'html', 'body': 'Welcome to the offic...      Lillia
 24  {'type': 'html', 'body': 'Welcome to the offic...         Mel
 25  {'type': 'html', 'body': 'Welcome to the offic...       Neeko
 26  {'type': 'html', 'body': 'Welcome to the offic...    Nocturne
 27  {'type': 'html', 'body': 'Welcome to the offic...     Orianna
 28  {'type': 'html', 'body': 'Welcome to the offic...      Samira
 29  {'type': 'html', 'body': 'Welcome to the offic...     Taliyah

                                       champion_update
 0   Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
 1             Base Stats\nBase attack damage : 68⇒ 66
 2   E - Rend\nTotal AD scaling on bonus damage per...
 3   R - Mantra\nEmpowered E - Defiance Bonus Prima...
 4   W - Ebb and Flow\nBounce Modifier : -10% (+10%...
 5   W - Bellows Breath\nBrittle Proc Damage : 10-1...
 6   E - Full Tilt\nMove Speed : 3s of 10%, increas...
 7   R - Insanity Potion\nBonus Stats : 25 / 60 / 9...
 8   R - Primordial Burst\nCooldown : 100 / 80 / 60...
 9   Q - Orb of Deception\nDamager per Pass : 40 / ...
 10  Q - Conquering Sands\nDamage AP Ratio : (+ 35%...
 11  Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
 12  Base Stats\nArmor Growth : 4.9 ⇒ 4.2\nQ - Ice ...
 13  Base Stats\nBase Attack Speed : 0.694 ⇒ 0.72\n...
 14                   Base Stats\nBase Armor : 43 ⇒ 37
 15  Q - Twilight Assault\nMonster Damage Cap : 120...
 16  Q - Shattered Earth\nMana Cost : 45 ⇒ 30\nThir...
 17     Base Stats\nAttack Speed Ratio : 0.694 ⇒ 0.725
 18  W - Dreaded Return\nSecondary Damage : 40 / 60...
 19  W - Twilight Shroud\nRestealth Timer : 1s / .9...
 20              Base Stats\nHealth Growth : 119 ⇒ 108
 21  Q - Decisive Strike\nMove speed duration : 1 /...
 22  Q - Sonic Wave / Resonating Strike\nBase Damag...
 23  Passive - Dream-Laden Bough\nMonster heal bonu...
 24  Passive - Searing Brilliance\nMinion Damage Mo...
 25  W - Shapeshifter\nSlightly-Less-Tricksy-Neekos...
 26  Passive - Umbra Blades\nCooldown : 13 ⇒ 12\nQ ...
 27  Q - Command: Attack\nCooldown : 6 / 5.25 / 4.5...
 28  Q - Flair\nThe Right Tool for the Job : Samira...
 29  Q - Threaded Volley\nBase Damage : 55 / 72.5 /...  ,
 2530)

In [9]:
patch_output_path = "lol_patch_notes_index.csv"
champion_output_path = "lol_patch_notes_champion_updates.csv"

patch_df.to_csv(patch_output_path, index=False, encoding="utf-8")
champion_updates_df.to_csv(champion_output_path, index=False, encoding="utf-8")

print(f"Saved patch index: {len(patch_df)} rows -> {patch_output_path}")
print(f"Saved champion updates: {len(champion_updates_df)} rows -> {champion_output_path}")

champion_updates_df.head(20)

Saved patch index: 162 rows -> lol_patch_notes_index.csv
Saved champion updates: 2530 rows -> lol_patch_notes_champion_updates.csv

,patch_title,patch_url,published_at,patch_summary,champion,champion_update
0,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Cassiopeia,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
1,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Graves,Base Stats\nBase attack damage : 68⇒ 66
2,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Kalista,E - Rend\nTotal AD scaling on bonus damage per...
3,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Karma,R - Mantra\nEmpowered E - Defiance Bonus Prima...
4,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Nami,W - Ebb and Flow\nBounce Modifier : -10% (+10%...
5,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Ornn,W - Bellows Breath\nBrittle Proc Damage : 10-1...
6,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Rell,"E - Full Tilt\nMove Speed : 3s of 10%, increas..."
7,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Singed,R - Insanity Potion\nBonus Stats : 25 / 60 / 9...
8,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Veigar,R - Primordial Burst\nCooldown : 100 / 80 / 60...
9,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Ahri,Q - Orb of Deception\nDamager per Pass : 40 / ...
10,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Azir,Q - Conquering Sands\nDamage AP Ratio : (+ 35%...
11,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Cassiopeia,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
12,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Lissandra,Base Stats\nArmor Growth : 4.9 ⇒ 4.2\nQ - Ice ...
13,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Olaf,Base Stats\nBase Attack Speed : 0.694 ⇒ 0.72\n...
14,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Pyke,Base Stats\nBase Armor : 43 ⇒ 37
15,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Shen,Q - Twilight Assault\nMonster Damage Cap : 120...
16,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Skarner,Q - Shattered Earth\nMana Cost : 45 ⇒ 30\nThir...
17,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Tryndamere,Base Stats\nAttack Speed Ratio : 0.694 ⇒ 0.725
18,League of Legends Patch 26.6 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-17 18:00:00+00:00,"{'type': 'html', 'body': 'It’s time for First ...",Zaahen,W - Dreaded Return\nSecondary Damage : 40 / 60...
19,League of Legends Patch 26.5 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-03 19:00:00+00:00,"{'type': 'html', 'body': 'Welcome to the offic...",Akali,W - Twilight Shroud\nRestealth Timer : 1s / .9...

## Data Cleaning

本节完成两件事：
1. 将发布时间统一到 `day` 粒度
2. 将 `champion_update` 的明细按项目拆分为多列（缺失值保留为 `NaN`）

In [11]:
def is_update_header(line: str) -> bool:
    line = clean_text(line)
    if not line:
        return False

    # 常见技能/属性标题
    if re.match(r"^(Base Stats|Passive|Q\s*-\s*|W\s*-\s*|E\s*-\s*|R\s*-\s*)", line, flags=re.I):
        return True

    # 兜底：短标题且不像完整句子
    if len(line) <= 45 and len(line.split()) <= 8 and not re.search(r"[.!?]$", line):
        if ":" not in line and ";" not in line:
            return True

    return False


def normalize_col_name(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"\s*-\s*", "_", s)
    s = re.sub(r"[^a-z0-9_]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return f"detail_{s}" if s else "detail_unknown"


def split_update_to_sections(update_text: str) -> Dict[str, str]:
    if not isinstance(update_text, str) or not update_text.strip():
        return {}

    lines = [clean_text(x) for x in update_text.split("\n") if clean_text(x)]
    if not lines:
        return {}

    sections: Dict[str, List[str]] = {}
    current_header = None

    for line in lines:
        if is_update_header(line):
            current_header = line
            sections.setdefault(current_header, [])
            continue

        if current_header is None:
            current_header = "General"
            sections.setdefault(current_header, [])

        sections[current_header].append(line)

    # 将每个 section 的多行明细合并成单字符串
    output = {}
    for k, v in sections.items():
        merged = " ".join(v).strip()
        output[k] = merged if merged else None

    return output


clean_df = champion_updates_df.copy()

# 1) 时间统一到 day 粒度
clean_df["date"] = pd.to_datetime(clean_df["published_at"], errors="coerce", utc=True).dt.floor("D")
clean_df["date"] = clean_df["date"].dt.tz_localize(None)

# 2) update 明细拆列
section_dicts = clean_df["champion_update"].apply(split_update_to_sections)
section_wide = pd.DataFrame(section_dicts.tolist())

# 原 section 名 -> 标准列名
rename_map = {c: normalize_col_name(c) for c in section_wide.columns}
section_wide = section_wide.rename(columns=rename_map)

# 同名列（标准化后冲突）做聚合合并
if section_wide.columns.duplicated().any():
    section_wide = section_wide.T.groupby(level=0).agg(
        lambda col: next((x for x in col if isinstance(x, str) and x.strip()), None)
    ).T

clean_df = pd.concat(
    [clean_df.drop(columns=["champion_update"]), section_wide],
    axis=1,
)

# 常用字段放前面
base_cols = ["date", "published_at", "patch_title", "champion", "patch_url", "patch_summary"]
detail_cols = [c for c in clean_df.columns if c.startswith("detail_")]
other_cols = [c for c in clean_df.columns if c not in base_cols + detail_cols]
clean_df = clean_df[base_cols + detail_cols + other_cols]

clean_output_path = "lol_patch_notes_champion_updates_cleaned.csv"
clean_df.to_csv(clean_output_path, index=False, encoding="utf-8")

print(f"Saved cleaned rows: {len(clean_df)} -> {clean_output_path}")
print(f"Detail columns: {len(detail_cols)}")
clean_df.head(20)

Saved cleaned rows: 2530 -> lol_patch_notes_champion_updates_cleaned.csv
Detail columns: 1581

,date,published_at,patch_title,champion,patch_url,patch_summary,detail_0_25_seconds,detail_10,detail_110,detail_1_25_seconds,...,detail_yone_abilities_rundown,detail_yone_biography,detail_yone_champion_insights,detail_yorick,detail_zeal,detail_zeri_abilities_rundown,detail_zeri_champion_bio,detail_zeri_champion_insights,detail_zeri_champion_trailer,detail_zilean
0,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Cassiopeia,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Graves,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Kalista,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Karma,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Nami,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Ornn,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Rell,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Singed,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Veigar,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Ahri,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Azir,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Cassiopeia,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
12,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Lissandra,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
13,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Olaf,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Pyke,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Shen,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Skarner,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
17,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Tryndamere,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
18,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Zaahen,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
19,2026-03-03,2026-03-03 19:00:00+00:00,League of Legends Patch 26.5 Notes,Akali,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Welcome to the offic...",None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

## 分类清洗（按改动类型分栏）

你要求的是“技能类改动放同一栏，并在栏内保留具体改动文本”。

此单元会输出这些列：
- `base_stats_changes`
- `passive_changes`
- `q_changes` / `w_changes` / `e_changes` / `r_changes`
- `other_changes`（其他非技能项）

若该记录没有对应类别改动，则该列为 `NaN`。

In [13]:
import numpy as np


def _is_header_line(line: str) -> bool:
    line = clean_text(line)
    if not line:
        return False

    # 常见标题形式：Base Stats / Passive / Q - xxx / W - xxx / E - xxx / R - xxx
    if re.match(r"^(Base Stats|Passive|Q\s*-\s*.+|W\s*-\s*.+|E\s*-\s*.+|R\s*-\s*.+)$", line, flags=re.I):
        return True

    return False


def _bucket_from_header(header: str) -> str:
    h = clean_text(header).lower()

    if h.startswith("base stats"):
        return "base_stats_changes"
    if h.startswith("passive"):
        return "passive_changes"
    if h.startswith("q -"):
        return "q_changes"
    if h.startswith("w -"):
        return "w_changes"
    if h.startswith("e -"):
        return "e_changes"
    if h.startswith("r -"):
        return "r_changes"

    return "other_changes"


def categorize_update_text(update_text: str) -> Dict[str, object]:
    buckets = {
        "base_stats_changes": [],
        "passive_changes": [],
        "q_changes": [],
        "w_changes": [],
        "e_changes": [],
        "r_changes": [],
        "other_changes": [],
    }

    if not isinstance(update_text, str) or not update_text.strip():
        return {k: np.nan for k in buckets.keys()}

    lines = [clean_text(x) for x in update_text.split("\n") if clean_text(x)]
    current_header = None
    current_bucket = "other_changes"

    for line in lines:
        if _is_header_line(line):
            current_header = line
            current_bucket = _bucket_from_header(line)
            # 把标题本身也保留在栏位里，便于回看
            buckets[current_bucket].append(f"[{current_header}]")
            continue

        buckets[current_bucket].append(line)

    # 每个类别合并成单列字符串；空值设为 NaN
    result = {}
    for k, v in buckets.items():
        merged = "\n".join(v).strip()
        result[k] = merged if merged else np.nan

    return result


categorized_df = champion_updates_df.copy()

# 1) 日期按 day 粒度
categorized_df["date"] = pd.to_datetime(categorized_df["published_at"], errors="coerce", utc=True).dt.floor("D")
categorized_df["date"] = categorized_df["date"].dt.tz_localize(None)

# 2) champion_update 分类拆列
cat_cols = categorized_df["champion_update"].apply(categorize_update_text).apply(pd.Series)
categorized_df = pd.concat([categorized_df, cat_cols], axis=1)

# 字段排序
ordered_cols = [
    "date",
    "published_at",
    "patch_title",
    "champion",
    "patch_url",
    "patch_summary",
    "base_stats_changes",
    "passive_changes",
    "q_changes",
    "w_changes",
    "e_changes",
    "r_changes",
    "other_changes",
    "champion_update",
]
ordered_cols = [c for c in ordered_cols if c in categorized_df.columns]
categorized_df = categorized_df[ordered_cols]

categorized_output_path = "lol_patch_notes_champion_updates_categorized.csv"
categorized_df.to_csv(categorized_output_path, index=False, encoding="utf-8")

print(f"Saved categorized rows: {len(categorized_df)} -> {categorized_output_path}")
categorized_df.head(20)

Saved categorized rows: 2530 -> lol_patch_notes_champion_updates_categorized.csv

,date,published_at,patch_title,champion,patch_url,patch_summary,base_stats_changes,passive_changes,q_changes,w_changes,e_changes,r_changes,other_changes,champion_update
0,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Cassiopeia,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",[Base Stats]\nBase Mana : 450 ⇒ 480,NaN,NaN,NaN,[E - Twin Fang]\nBonus Magic Damage : 20 / 43 ...,NaN,NaN,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
1,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Graves,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",[Base Stats]\nBase attack damage : 68⇒ 66,NaN,NaN,NaN,NaN,NaN,NaN,Base Stats\nBase attack damage : 68⇒ 66
2,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Kalista,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,NaN,[E - Rend]\nTotal AD scaling on bonus damage p...,NaN,NaN,E - Rend\nTotal AD scaling on bonus damage per...
3,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Karma,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,NaN,NaN,[R - Mantra]\nEmpowered E - Defiance Bonus Pri...,NaN,R - Mantra\nEmpowered E - Defiance Bonus Prima...
4,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Nami,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,[W - Ebb and Flow]\nBounce Modifier : -10% (+1...,NaN,NaN,NaN,W - Ebb and Flow\nBounce Modifier : -10% (+10%...
5,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Ornn,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,[W - Bellows Breath]\nBrittle Proc Damage : 10...,NaN,NaN,NaN,W - Bellows Breath\nBrittle Proc Damage : 10-1...
6,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Rell,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,NaN,"[E - Full Tilt]\nMove Speed : 3s of 10%, incre...",[R - Magnet Storm]\nDamage : 120 / 200 / 280 (...,NaN,"E - Full Tilt\nMove Speed : 3s of 10%, increas..."
7,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Singed,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,NaN,NaN,[R - Insanity Potion]\nBonus Stats : 25 / 60 /...,NaN,R - Insanity Potion\nBonus Stats : 25 / 60 / 9...
8,2026-03-31,2026-03-31 18:00:00+00:00,League of Legends Patch 26.7 Notes,Veigar,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Tons of fun and frie...",NaN,NaN,NaN,NaN,NaN,[R - Primordial Burst]\nCooldown : 100 / 80 / ...,NaN,R - Primordial Burst\nCooldown : 100 / 80 / 60...
9,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Ahri,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",NaN,NaN,[Q - Orb of Deception]\nDamager per Pass : 40 ...,NaN,NaN,NaN,NaN,Q - Orb of Deception\nDamager per Pass : 40 / ...
10,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Azir,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",NaN,NaN,[Q - Conquering Sands]\nDamage AP Ratio : (+ 3...,[W - Arise!]\nDamage : 0-45 (5 damage per leve...,NaN,NaN,NaN,Q - Conquering Sands\nDamage AP Ratio : (+ 35%...
11,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Cassiopeia,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",[Base Stats]\nBase Mana : 450 ⇒ 480,NaN,NaN,NaN,[E - Twin Fang]\nBonus Magic Damage to Poisone...,NaN,NaN,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
12,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Lissandra,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",[Base Stats]\nArmor Growth : 4.9 ⇒ 4.2,NaN,[Q - Ice Shard]\nCooldown : 8 / 7 / 6 / 5 / 4 ...,NaN,NaN,NaN,NaN,Base Stats\nArmor Growth : 4.9 ⇒ 4.2\nQ - Ice ...
13,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Olaf,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",[Base Stats]\nBase Attack Speed : 0.694 ⇒ 0.72,NaN,[Q - Undertow]\nSlow Amount : 25 / 30 / 40 / 4...,[W - Tough it Out]\nBug Fix : If you cast W wh...,[E - Reckless Swing]\nDamage to Self : 30% of ...,NaN,NaN,Base Stats\nBase Attack Speed : 0.694 ⇒ 0.72\n...
14,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Pyke,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",[Base Stats]\nBase Armor : 43 ⇒ 37,NaN,NaN,NaN,NaN,NaN,NaN,Base Stats\nBase Armor : 43 ⇒ 37
15,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Shen,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",NaN,NaN,[Q - Twilight Assault]\nMonster Damage Cap : 1...,NaN,NaN,NaN,NaN,Q - Twilight Assault\nMonster Damage Cap : 120...
16,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Skarner,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",NaN,NaN,[Q - Shattered Earth]\nMana Cost : 45 ⇒ 30\nTh...,NaN,NaN,NaN,NaN,Q - Shattered Earth\nMana Cost : 45 ⇒ 30\nThir...
17,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Tryndamere,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",[Base Stats]\nAttack Speed Ratio : 0.694 ⇒ 0.725,NaN,NaN,NaN,NaN,NaN,NaN,Base Stats\nAttack Speed Ratio : 0.694 ⇒ 0.725
18,2026-03-17,2026-03-17 18:00:00+00:00,League of Legends Patch 26.6 Notes,Zaahen,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'It’s time for First ...",NaN,NaN,NaN,[W - Dreaded Return]\nSecondary Damage : 40 / ...,[E - Aureate Rush]\nBonus Damage to Monsters :...,NaN,NaN,W - Dreaded Return\nSecondary Damage : 40 / 60...
19,2026-03-03,2026-03-03 19:00:00+00:00,League of Legends Patch 26.5 Notes,Akali,https://www.leagueoflegends.com/en-us/news/gam...,"{'type': 'html', 'body': 'Welcome to the offic...",NaN,NaN,NaN,[W - Twilight Shroud]\nRestealth Timer : 1s / ...,NaN,NaN,NaN,W - Twilight Shroud\nRestealth Timer : 1s / .9...

In [15]:
champion_updates_df.head(100)

,patch_title,patch_url,published_at,patch_summary,champion,champion_update
0,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Cassiopeia,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
1,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Graves,Base Stats\nBase attack damage : 68⇒ 66
2,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Kalista,E - Rend\nTotal AD scaling on bonus damage per...
3,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Karma,R - Mantra\nEmpowered E - Defiance Bonus Prima...
4,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Nami,W - Ebb and Flow\nBounce Modifier : -10% (+10%...
...,...,...,...,...,...,...
95,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Gwen,Passive - A Thousand Cuts\nMonster Damage Cap ...
96,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Jayce,Q - To the Skies / Shock Blast\nBonus Damage t...
97,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Lillia,Passive - Dream-Laden Bough\nHeal Against Larg...
98,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Malphite,W - Thunderclap\nMonster Damage : 2x ⇒ 1.8x\nE...
99,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Master Yi,Base Stats\nArmor Growth : 4.2 ⇒ 4.5\nQ - Alph...

In [17]:
# 统一导出（推荐运行这个单元，避免文件名混淆）
# 说明：
# - patch_df: patch note 索引（每篇一行）
# - champion_updates_df: 原始英雄改动明细（每个英雄一行）
# - categorized_df: 分类清洗后的明细

export_files = {
    # 为兼容旧文件名，这里把 lol_patch_notes.csv 也导出成“全量索引”
    "lol_patch_notes.csv": patch_df,
    "lol_patch_notes_index.csv": patch_df,
    "lol_patch_notes_raw.csv": champion_updates_df,
    "lol_patch_notes_champion_updates.csv": champion_updates_df,
}

# 如果你已经运行了分类单元，也一并导出
if "categorized_df" in globals():
    export_files["lol_patch_notes_champion_updates_categorized.csv"] = categorized_df

for file_name, data in export_files.items():
    data.to_csv(file_name, index=False, encoding="utf-8")
    print(f"Saved {file_name}: rows={len(data)}")

print("Done. You can open lol_patch_notes.csv safely now.")

Saved lol_patch_notes.csv: rows=162
Saved lol_patch_notes_index.csv: rows=162
Saved lol_patch_notes_raw.csv: rows=2530
Saved lol_patch_notes_champion_updates.csv: rows=2530
Saved lol_patch_notes_champion_updates_categorized.csv: rows=2530
Done. You can open lol_patch_notes.csv safely now.

In [16]:
# 导出原始抓取数据（未做分类清洗）
raw_output_path = "lol_patch_notes_raw.csv"

# champion_updates_df 为逐篇解析后的原始明细（包含 champion_update 原始文本）
champion_updates_df.to_csv(raw_output_path, index=False, encoding="utf-8")

print(f"Saved raw rows: {len(champion_updates_df)} -> {raw_output_path}")
champion_updates_df.head(100)

Saved raw rows: 2530 -> lol_patch_notes_raw.csv

,patch_title,patch_url,published_at,patch_summary,champion,champion_update
0,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Cassiopeia,Base Stats\nBase Mana : 450 ⇒ 480\nE - Twin Fa...
1,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Graves,Base Stats\nBase attack damage : 68⇒ 66
2,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Kalista,E - Rend\nTotal AD scaling on bonus damage per...
3,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Karma,R - Mantra\nEmpowered E - Defiance Bonus Prima...
4,League of Legends Patch 26.7 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-03-31 18:00:00+00:00,"{'type': 'html', 'body': 'Tons of fun and frie...",Nami,W - Ebb and Flow\nBounce Modifier : -10% (+10%...
...,...,...,...,...,...,...
95,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Gwen,Passive - A Thousand Cuts\nMonster Damage Cap ...
96,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Jayce,Q - To the Skies / Shock Blast\nBonus Damage t...
97,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Lillia,Passive - Dream-Laden Bough\nHeal Against Larg...
98,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Malphite,W - Thunderclap\nMonster Damage : 2x ⇒ 1.8x\nE...
99,Patch 26.2 Notes,https://www.leagueoflegends.com/en-us/news/gam...,2026-01-21 19:00:00+00:00,"{'type': 'html', 'body': 'Patch 26.2 ready to ...",Master Yi,Base Stats\nArmor Growth : 4.2 ⇒ 4.5\nQ - Alph...